name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ] 
  pull_request_review:
    types: 
      - submitted
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
     
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Build with Gradle
      run: ./gradlew clean build
      
    - name: Build APK
      run: ./gradlew assembleDebug --stacktrace
      
    - name: Generate Debug Apk
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Download APK from build
      uses: actions/download-artifact@v1
      with:
        name: apk
      
    - name: Trigger pr-autobuild action for building PR
      uses: nikhilaii93/pr-autobuild@master
      env:
          GITHUB_TOKEN: ${{ secrets.bot_token }}
          GITHUB_NAME: rohmatjulianto
          DEFAULT_APPROVAL_COUNT_ENV: 1
          BUILD_COMMENT_ENV: "OK to test"
          PR_LABEL_ENV: RELEASE_TEST
          
    - name: Trigger pr-autobuild action
      uses: nikhilaii93/pr-autobuild@master
      env:
        GITHUB_TOKEN: ${{ secrets.bot_token }}
        GITHUB_NAME: rohmatjulianto
        DEFAULT_APPROVAL_COUNT_ENV: 1
        BUILD_COMMENT_ENV: "OK to test"
        PR_LABEL_ENV: RELEASE
        DEFAULT_MERGE: squash
        DELETE_BRANCH_ENV: true
